### PR TITLE
#6/feat: adjust directory structure

### PR DESCRIPTION
**Pull request by gatheluck**
## Issue URL

Before start working on following issue. I adjust directory structure by this PR to prevent future conflicts.
#6 

## Change overview

Adjust directory structure based on following figure.
https://user-images.githubusercontent.com/21344007/232263137-9bf6d751-47ee-4921-a056-ab8afeaadad7.png

## How to test

Please compare the figure and updated directory strucutre.

## Note for reviewers

- All files added in this PR is just copied from original one. So reviewers don't have to check contents of added files.
- #8 should be merged first to deactivate CI.

### CODE REVIEW

**Review by YoshikiKubotani — CHANGES_REQUESTED** [review]
As I have already removed two files related to GitHub Actions on [this commit](https://github.com/cvpaperchallenge/Crux/commit/22b3c8a470e6a16a53edd38fc89136dbb4f9d1aa), we might need to remove the same files from this branch as well to avoid conflicts.

Or, in this case, would it be able to merge successfully?

**Review by YoshikiKubotani — APPROVED** [review]
Please forget the above comments.

I believe this commit does not generate any conflicts because there are no parallel changes both on develop and this branch.

As for the structure, LGTM.

**Comment by gatheluck** [comment]
@YoshikiKubotani Sorry small conflicts occured in `pyproject.toml` and `docker-compose.yaml` file for gpu. The way to resolve was very straight forward so I think no problem. But could you double check for sure?

**Review by YoshikiKubotani — APPROVED** [review]
Thank you.
I checked it out; there seem to be no problems.

**Pull request merged**
